In [1]:
import torch

In [2]:
from __future__ import print_function

In [3]:
#构造一个未初始化的矩阵
x = torch.empty(5,3)
print(x)

tensor([[-8.3317e+17,  4.5869e-41,  9.2198e-39],
        [ 1.8381e-40,  0.0000e+00,  2.5244e-29],
        [ 0.0000e+00,  2.5244e-29,  1.8361e+25],
        [ 1.4603e-19,  6.4069e+02,  2.7489e+20],
        [ 1.5444e+25,  1.6217e-19,  7.0062e+22]])


In [4]:
#构造一个随机初始化的矩阵
x = torch.rand(5,3)
print(x)

tensor([[0.0777, 0.8518, 0.1810],
        [0.4824, 0.6920, 0.5830],
        [0.0606, 0.6420, 0.3073],
        [0.0935, 0.7858, 0.7351],
        [0.0919, 0.4016, 0.8670]])


In [5]:
#构造一个0填充的且dtype long的矩阵
x = torch.zeros(5,3,dtype=torch.long)

In [6]:
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [7]:
print(type(x))

<class 'torch.Tensor'>


In [8]:
x[1]

tensor([0, 0, 0])

In [9]:
x[0][0]

tensor(0)

In [10]:
type(x[0][0])

torch.Tensor

In [11]:
#直接从数据构造张量
x = torch.tensor([4.4,3])
print(x)

tensor([4.4000, 3.0000])


In [12]:
x = x.new_ones(5,3,dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [13]:
x = torch.randn_like(x, dtype=torch.float)
x

tensor([[ 1.9875,  0.0732,  1.0035],
        [-0.7549, -0.8295, -0.0205],
        [-0.1700, -0.8002,  0.0171],
        [-1.8364,  0.2177,  0.2655],
        [-1.7763,  1.6139, -0.9225]])

In [14]:
#张量的大小
x.size()

torch.Size([5, 3])

In [19]:
#加法
y = torch.rand(5,3)
print(x)
print(y)
print(x+y)
#加法2
print('加法2')
print(torch.add(x,y))

tensor([[ 1.9875,  0.0732,  1.0035],
        [-0.7549, -0.8295, -0.0205],
        [-0.1700, -0.8002,  0.0171],
        [-1.8364,  0.2177,  0.2655],
        [-1.7763,  1.6139, -0.9225]])
tensor([[0.1957, 0.8940, 0.1708],
        [0.1986, 0.9980, 0.2928],
        [0.3862, 0.8003, 0.1611],
        [0.7501, 0.8581, 0.7240],
        [0.0702, 0.3595, 0.4619]])
tensor([[ 2.1832e+00,  9.6720e-01,  1.1743e+00],
        [-5.5635e-01,  1.6852e-01,  2.7237e-01],
        [ 2.1619e-01,  5.2154e-05,  1.7820e-01],
        [-1.0862e+00,  1.0758e+00,  9.8952e-01],
        [-1.7061e+00,  1.9734e+00, -4.6067e-01]])
加法2
tensor([[ 2.1832e+00,  9.6720e-01,  1.1743e+00],
        [-5.5635e-01,  1.6852e-01,  2.7237e-01],
        [ 2.1619e-01,  5.2154e-05,  1.7820e-01],
        [-1.0862e+00,  1.0758e+00,  9.8952e-01],
        [-1.7061e+00,  1.9734e+00, -4.6067e-01]])


In [20]:
#提供一个参数，作为计算结果的接收
result = torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[ 2.1832e+00,  9.6720e-01,  1.1743e+00],
        [-5.5635e-01,  1.6852e-01,  2.7237e-01],
        [ 2.1619e-01,  5.2154e-05,  1.7820e-01],
        [-1.0862e+00,  1.0758e+00,  9.8952e-01],
        [-1.7061e+00,  1.9734e+00, -4.6067e-01]])


In [21]:
#直接将一个张量加到另一个张量上
print('add:',end='')
y.add(x)
print(y)
print('add_:',end='')# 就地改变y的值
print(y)

add:tensor([[0.1957, 0.8940, 0.1708],
        [0.1986, 0.9980, 0.2928],
        [0.3862, 0.8003, 0.1611],
        [0.7501, 0.8581, 0.7240],
        [0.0702, 0.3595, 0.4619]])
add_tensor([[0.1957, 0.8940, 0.1708],
        [0.1986, 0.9980, 0.2928],
        [0.3862, 0.8003, 0.1611],
        [0.7501, 0.8581, 0.7240],
        [0.0702, 0.3595, 0.4619]])


In [24]:
print(x)
print(x[:,-1])
print(x[:,0])
print(x[-1:])

tensor([[ 1.9875,  0.0732,  1.0035],
        [-0.7549, -0.8295, -0.0205],
        [-0.1700, -0.8002,  0.0171],
        [-1.8364,  0.2177,  0.2655],
        [-1.7763,  1.6139, -0.9225]])
tensor([ 1.0035, -0.0205,  0.0171,  0.2655, -0.9225])
tensor([ 1.9875, -0.7549, -0.1700, -1.8364, -1.7763])
tensor([[-1.7763,  1.6139, -0.9225]])


In [27]:
#调整张量的大小和形状
x = torch.rand(4,4) #均匀分布[0,1)之间
x = torch.randn(4,4)#标准正态分布，均值为0，方差为0
y = x.view(16)
z = x.view(-1, 8) #这里的-1意思是通过其他的尺寸来推算该位置的值，这里就是说通过总共大小16和一个方向为8，推算该位置为几。
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [28]:
#通过.item()将张量的值作为python数字获取
x = torch.randn(1)
x.item()

-0.20025917887687683

In [29]:
type(x.item())

float

In [33]:
x = torch.randn(2,2)
x[0][0].item()

-1.1447744369506836

In [34]:
# numpy bridge
# 将torch张量转换为numpy数组，反之亦然
# torch tensor和numpy数组将共享内存位置（如果tensor在cpu上）

# tensor转换为numpy
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [35]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [36]:
a.add_(1)
a

tensor([2., 2., 2., 2., 2.])

In [37]:
b

array([2., 2., 2., 2., 2.], dtype=float32)

In [38]:
import numpy as np

In [40]:
# numpy转换为tensor
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a, b)

[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [ ]:
#autograd:自动微分（automatic differentiation）
'''
该autograd包是pytorch中所有神经的核心。让我们简单地访问它，然后
训练我们第一个基于torch的神经网络。
该autograd软件包为tensor上的所有操作提供自动微分。他是一个由运行定义的框架，
这意味着以代码运行方式定义你的后向传播，并且每次迭代都可以不同。我们从tensor和gradients来举一些例子。

1. 张量
torch.tensor是程序的中心类。如果将其属性设置.requires_grad为Ture，它将开始跟踪对其的所有操作。
完成计算后，可以调用.backward()并自动计算所有的梯度。该张量的梯度将累加到.grad属性中。
要停止张量跟踪历史记录，调用.detach()将其从计算历史记录中分离出来，并防止跟踪将来
的计算。
要停止跟踪历史记录（和使用内存），还可以将代码块包装在torch.no_grad()中：这在评估模型时特别有
用，因为模型的可训练参数有requires_grad=Ture，但我们在评估阶段不需要它梯度。

还有一个类对autograd实现非常重要那就是Function。Tensor和Function相互连接并构建一个非循环图，它保存整个完整的计算过程的历史信息。
每个张量都有一个.grad_fn属性保存着创建了张量的Function的引用，（如果用户自己创建张量，则grad_fn是None）。

如果向计算倒数，可以调用Tensor.backward()。如果Tensor是标量（即它包含一个元素数据），则不需要制定任何参数backward（），但是如果他有更多元素，则需要指定
一个gradient参数来指定张量的形状。

'''
