In [2]:
import torch
from torch import nn
from torch.nn import functional as F

In [9]:
class TextNet(nn.Module):
    def __init__(self, vocab_size, seq_len, embedding_len, num_classes=2):
        super(TextNet, self).__init__()
        self.seq_len = seq_len
        self.vocab_size= vocab_size
        self.embedding_len = embedding_len
        self.word_embeddings = nn.Embedding(vocab_size, embedding_len)
        
    def forward(self, x):
        x = self.word_embeddings(x)
        return x

In [11]:
model = TextNet(vocab_size=5000, seq_len=600, embedding_len=2)
x = [[1,2,2,4]]
input1 = torch.autograd.Variable(torch.LongTensor(x))
print(input1)
o = model(input1)
print(o)
print(o.size())

x = [[1,3,2,4]]
input2 = torch.autograd.Variable(torch.LongTensor(x))
o = model(input2)
print(o)
print(o.size())

tensor([[1, 2, 2, 4]])
tensor([[[-1.1069,  0.1948],
         [-0.8218,  0.0227],
         [-0.8218,  0.0227],
         [ 0.3907,  0.3755]]], grad_fn=<EmbeddingBackward>)
torch.Size([1, 4, 2])
tensor([[[-1.1069,  0.1948],
         [-0.5894,  0.1793],
         [-0.8218,  0.0227],
         [ 0.3907,  0.3755]]], grad_fn=<EmbeddingBackward>)
torch.Size([1, 4, 2])
